apiVersion: v1
kind: Pod
metadata:
  name: renata-yaml-test
spec:
  containers:
  - name: animals
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: app-storage
      mountPath: storage
  - name: spring-music
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: app-storage
      mountPath: storage
  volumes:
  - name: app-storage
    emptyDir: {}