apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
  labels:
    app:cuda-test
    env:prod
spec:
  containers:
    - name: cuda-test
      image: "yanivomc/spring-music:latest"
  nodeSelector:
    env: prod
